
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/weato-logging/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu



hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180

    - location: scripts/health_check.sh
      timeout: 180

    - location: scripts/switch.sh
      timeout: 180