spring:
  datasource:
    url: jdbc:mysql://mysql.cyvxohfasm5y.ap-northeast-2.rds.amazonaws.com:3306/ceos15
    username: ceos15
    password: qorwlgns12!
#    driver-class-name: org.h2.Driver
  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: create #entity를 생성시점에 지우고 다 다시 생성
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1ODY2Njg1OCwiaWF0IjoxNjU4NjY2ODU4fQ.Qf32zRz87cGgQ6XEbzkRyrDfharymBhqYIhYGcPBclmwtp1wTpLrRUrUyiEj-NiOLvDbiAnc85--_QHCDhZ9_w
  token-validity-in-seconds: 86400

