spring:
  datasource:
    url: jdbc:mysql://mysql.cyvxohfasm5y.ap-northeast-2.rds.amazonaws.com:3306/ceos15
    username: ceos15
    password: qorwlgns12!
#    driver-class-name: org.h2.Driver
  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: update #다른 부분만 바꿈
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: 'eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1ODY2Njg1OCwiaWF0IjoxNjU4NjY2ODU4fQ.Qf32zRz87cGgQ6XEbzkRyrDfharymBhqYIhYGcPBclmwtp1wTpLrRUrUyiEj-NiOLvDbiAnc85--_QHCDhZ9_w'

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 180000
    refreshTokenExpiry: 604800000
  oauth2:
    authorized-redirect-uris: http://localhost:3000, http://weato.net, http://localhost:8080, http://3.37.94.86


logging-module:
  version: 0.0.10

