spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: QKR6g9QcGNlCUP7CUdTa
            client-secret: LQbKCSr0xm
            client-authentication-method: post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthyear
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
